# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage-service-backend
  labels:
    app: file-storage-service-backend
  namespace: smkz-for-work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-storage-service-backend
  template:
    metadata:
      labels:
        app: file-storage-service-backend
    spec:
      volumes:
        - name: files-volume
          persistentVolumeClaim:
            claimName: file-storage-service-pvc
      containers:
        - name: file-storage-service-backend
          image: $secrets.REGISTRY_URL/file-storage-service-backend:latest
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 250m
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: file-storage-service-secrets
                  key: database.host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: file-storage-service-configs
                  key: database.port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: file-storage-service-configs
                  key: database.name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: file-storage-service-secrets
                  key: database.username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-storage-service-secrets
                  key: database.password
            - name: SINGLE_SIGN_ON_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: file-storage-service-configs
                  key: services.singlesignon
            - name: REQUEST_CLIENT_VERIFY_SSL
              valueFrom:
                configMapKeyRef:
                  name: file-storage-service-configs
                  key: request.verifyssl
          volumeMounts:
            - mountPath: "/usr/share/nginx/html/storage/app/files"
              name: files-volume
              subPath: files
            - mountPath: "/usr/share/nginx/html/storage/app/temps"
              name: files-volume
              subPath: temps
            - mountPath: "/usr/share/nginx/html/storage/app/zips"
              name: files-volume
              subPath: zips
      securityContext:
        runAsGroup: www-data
        fsGroup: www-data

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: file-storage-service-backend
  namespace: smkz-for-work
spec:
  type: ClusterIP
  selector:
    app: file-storage-service-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
